/* Generated By:JJTree: Do not edit this line. ASTARGUMENTS.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARGUMENTS extends SimpleNode {
  public ASTARGUMENTS(int id) {
    super(id);
  }

  public ASTARGUMENTS(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ca7bcddd3d92467d2bcaa9f27cc5c12e (do not edit this line) */
