/* Generated By:JJTree: Do not edit this line. ASTARRAY_ACESS.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARRAY_ACESS extends SimpleNode {
  public ASTARRAY_ACESS(int id) {
    super(id);
  }

  public ASTARRAY_ACESS(Jmm p, int id) {
    super(p, id);
  }
  
  public boolean doSemanticAnalysis(StringBuilder info) throws SemanticException {
	  
	  
	  boolean result = true;
	  
	  if(this.children != null) {
		  for(Node node : this.children) {
			  boolean r = ((SimpleNode) node).doSemanticAnalysis(info);
			  result = result && r;
		  }
	  }
	  
	  if(result == false)
		  return false;
	  
	  SimpleNode lhn  = (SimpleNode) this.children[0];
	  if(lhn.toString().equals("IDENTIFIER")) {
		  if(this.simbolTable.isSimbolKnown(lhn.name) == false){

			  System.out.println("Error on line " + this.lineNo + ", column " + this.columnNo + ": Simbol " + lhn.name + " is not known.");
			  this.decrementMaxErros();
			  return false;
		  }else {
			  Simbol s = this.simbolTable.getSimbol(lhn.name);
			  if(s == null){

				  System.out.println("Error on line " + this.lineNo + ", column " + this.columnNo + ": Simbol " + lhn.name + " is not known.");
				  this.decrementMaxErros();
				  return false;
			  }else if(s.isInitialized == false 
					  && !(info.toString().split(" ")[0].equals("IF:") && s.ifInitialized)
					  && !(info.toString().split(" ")[0].equals("ELSE:") && s.elseInitialized)){
				  if(s.condInitialized) {
					  System.out.println("Warning on line " + this.lineNo + ", column " + this.columnNo + ": Simbol " + lhn.name + " may not have been initiated.");
				  }else {
					  System.out.println("Error on line " + this.lineNo + ", column " + this.columnNo + ": Simbol " + lhn.name + " has not been initiated.");
					  this.decrementMaxErros();
					  return false;
				  }
			  }else
				  lhn.type = s.getType().getName();
			  
			  if(s.getType().content == null) {
				  System.out.println("Error on line " + this.lineNo + ", column " + this.columnNo + ": Simbol " + lhn.name + " must be an array.");
				  this.decrementMaxErros();
				  return false;
			  }
		  }
		  
		  this.type = lhn.type;
	  }else if(lhn.toString().equals("FUNCTION")) {
		  if(this.descriptors.getDescriptor(lhn.type).content == null) {
			  System.out.println("Error on line " + this.lineNo + ", column " + this.columnNo + ": Fucntion " + lhn.name + " must be an array.");
			  this.decrementMaxErros();
			  return false;
		  }
	  }
	  else {
		  System.out.println("Error on line " + this.lineNo + ", column " + this.columnNo + ": Not suported");
		  this.decrementMaxErros();
		  return false;
	  }
	  
	  if(this.jjtGetNumChildren() == 2) {
		  SimpleNode rhn  = (SimpleNode) this.children[1];
		  if(!rhn.type.equals("int")) {
			  System.out.println("Error on line " + rhn.lineNo + ", column " + rhn.columnNo + ": Index must be int");
			  this.decrementMaxErros();
			  return false;
		  }
		  this.type = this.descriptors.getDescriptor(lhn.type).content.getName();
	  }else return false;
	  
	  //System.out.println("Type: " + this.type);
	  
	  return result;
  }
}
/* JavaCC - OriginalChecksum=fcfe188a839bbdc2a2c0779ea2968e4a (do not edit this line) */
