/* Generated By:JJTree: Do not edit this line. ASTARRAY_ACESS.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARRAY_ACESS extends SimpleNode {
  public ASTARRAY_ACESS(int id) {
    super(id);
  }

  public ASTARRAY_ACESS(Jmm p, int id) {
    super(p, id);
  }
  
  public boolean doSemanticAnalysis() {
	  
	  
	  boolean result = true;
	  
	  if(this.children != null) {
		  for(Node node : this.children) {
			  boolean r = ((SimpleNode) node).doSemanticAnalysis();
			  result = result && r;
		  }
	  }
	  
	  if(result == false)
		  return false;
	  
	  SimpleNode lhn  = (SimpleNode) this.children[0];
	  if(lhn.toString().equals("IDENTIFIER")) {
		  if(this.simbolTable.isSimbolKnown(lhn.name) == false){
			  System.out.println("Simbol " + lhn.name + " is not known.");
			  return false;
		  }else {
			  lhn.type = this.simbolTable.getSimbol(lhn.name).getType().getName();
		  }
		  this.type = lhn.type;
	  }else return false;
	  
	  if(this.jjtGetNumChildren() == 2) {
		  SimpleNode rhn  = (SimpleNode) this.children[1];
		  if(!rhn.type.equals("int")) {
			  System.out.println("Index must be int");
			  return false;
		  }
		  this.type = this.descriptors.getDescriptor(lhn.type).content.getName();
	  }else return false;
	  
	  //System.out.println("Type: " + this.type);
	  
	  return result;
  }
}
/* JavaCC - OriginalChecksum=fcfe188a839bbdc2a2c0779ea2968e4a (do not edit this line) */
