/* Generated By:JJTree: Do not edit this line. ASTBODY.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBODY extends SimpleNode {
  public ASTBODY(int id) {
    super(id);
  }

  public ASTBODY(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3f7fa0ac7bb8e32c665c89cbe56d3da9 (do not edit this line) */
