/* Generated By:JJTree: Do not edit this line. ASTBOOL.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBOOL extends SimpleNode {
  public ASTBOOL(int id) {
    super(id);
  }

  public ASTBOOL(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=406511056626b08d849a85418d68d209 (do not edit this line) */
