/* Generated By:JJTree: Do not edit this line. ASTCONDITION.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCONDITION extends SimpleNode {
  public ASTCONDITION(int id) {
    super(id);
  }

  public ASTCONDITION(Jmm p, int id) {
    super(p, id);
  }
  
	public boolean doSemanticAnalysis(StringBuilder info) {
		  
		  
		  boolean result = true;
		  
		  if(this.children != null) {
			  for(Node node : this.children) {
				  boolean r = ((SimpleNode) node).doSemanticAnalysis(info);
				  result = result && r;
			  }
		  }
		  
		  if(result == false)
			  return false;
		  
		  if(((SimpleNode) this.children[0]).type != "boolean") {
			  System.out.println("Error on line " + this.lineNo + ", column " + this.columnNo + ": Condition must be boolean.");
			  return false;
		  }
		  return result;
	}

}
/* JavaCC - OriginalChecksum=b62e59fc6de0357b45a6442c843143e4 (do not edit this line) */
