/* Generated By:JJTree: Do not edit this line. ASTCLASS.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCLASS extends SimpleNode {
  public ASTCLASS(int id) {
    super(id);
  }

  public ASTCLASS(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c5a10aee2ca1e39f551c52301e2f6d0f (do not edit this line) */
