/* Generated By:JJTree: Do not edit this line. ASTCODE_BLOCK.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCODE_BLOCK extends SimpleNode {
  public ASTCODE_BLOCK(int id) {
    super(id);
    this.has_scope = true;
  }

  public ASTCODE_BLOCK(Jmm p, int id) {
    super(p, id);
    this.has_scope = true;
  }

}
/* JavaCC - OriginalChecksum=af350bf54633cc4f67ff488f8a93ff31 (do not edit this line) */
