/* Generated By:JJTree: Do not edit this line. ASTCLASS_DECL.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.util.ArrayList;

public
class ASTCLASS_DECL extends SimpleNode {
  public ASTCLASS_DECL(int id) {
    super(id);
    this.has_scope = true;
  }

  public ASTCLASS_DECL(Jmm p, int id) {
    super(p, id);
    this.has_scope = true;
  }
  
  public boolean createTable() throws SemanticException {
	  
	  
	  if(this.parent != null) {
		 this.functionTable = ((SimpleNode)this.parent).functionTable;
		 this.descriptors = ((SimpleNode)this.parent).descriptors;
	  }
	  
	  if(this.has_scope == false && this.parent != null) {
		  this.simbolTable = ((SimpleNode)this.parent).simbolTable;
	  }
	  else if(this.has_scope == true){
		  this.simbolTable = new SimbolTable();
		  if(this.parent != null){
			  this.simbolTable.setParent( ( (SimpleNode)this.parent ).simbolTable);
		  }
	  }
	  this.simbolTable.setGlobal(true);
	  
	  this.descriptors.addDescriptor( "this", this.name, this.simbolTable);
	  this.descriptors.addDescriptor( this.name, this.name, this.simbolTable);

	  
	  if(this.children != null) {
		  SimpleNode lhn  = (SimpleNode) this.children[0];
		  if(lhn.toString().equals("EXTENDS")) {
			  Descriptor d = this.descriptors.getDescriptor(lhn.name);
			  if(d == null) {
				  System.out.println(lhn.name + " is not known");
				  this.decrementMaxErros();
				  return false;
			  }else {
				  this.descriptors.getDescriptor("this").extend = d;
				  this.descriptors.getDescriptor(this.name).extend = d;
			  }
		  }
	  }
	  
	  this.simbolTable.addSimbol(this.descriptors.getDescriptor("this"),"this",true);
	  
	  
	  boolean result = true;
	  	  
	   
	  if(this.children != null) {
		  for(Node node : this.children) {
			  boolean r = ((SimpleNode) node).createTable();
			  result = result && r;
		  }
	  }
	  
	  if(hasConstructor == false) {
		  Descriptor ds = this.descriptors.getDescriptor("this");
		  ds.addParams(new ArrayList<Descriptor>());
		  ds = this.descriptors.getDescriptor(this.name);
		  ds.addParams(new ArrayList<Descriptor>());
	  }

	  return result;
  }
}
/* JavaCC - OriginalChecksum=b2f9e939c7dbed29080db488c438e1c4 (do not edit this line) */
