/* Generated By:JJTree: Do not edit this line. ASTEXTENDS.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEXTENDS extends SimpleNode {
  public ASTEXTENDS(int id) {
    super(id);
  }

  public ASTEXTENDS(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=968506e1fd68750836d9f7a1921dd865 (do not edit this line) */
