/* Generated By:JJTree: Do not edit this line. ASTEXPRESSION.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEXPRESSION extends SimpleNode {
  public ASTEXPRESSION(int id) {
    super(id);
  }

  public ASTEXPRESSION(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c9d5eb86f9eb1656bb1ef2e1876f7e1b (do not edit this line) */
