/* Generated By:JJTree: Do not edit this line. ASTEXPRESSION.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEXPRESSION extends SimpleNode {
  public ASTEXPRESSION(int id) {
    super(id);
  }

  public ASTEXPRESSION(Jmm p, int id) {
    super(p, id);
  }

	public boolean doSemanticAnalysis(StringBuilder info) throws SemanticException {
		  
		  
		  boolean result = true;
		  
		  if(this.children != null) {
			  for(Node node : this.children) {
				  boolean r = ((SimpleNode) node).doSemanticAnalysis(info);
				  result = result && r;
			  }
		  }
		  
		  if(result == false)
			  return false;
		  
		  SimpleNode lhn  = (SimpleNode) this.children[0];
		  this.lineNo = lhn.lineNo;
		  if(lhn.toString().equals("IDENTIFIER")) {
			  if(this.simbolTable.isSimbolKnown(lhn.name) == false){
				  System.out.println("Error on line " + this.lineNo + ": Simbol " + lhn.name + " is not known.");
				  this.decrementMaxErros();
				  return false;
			  }else {
				  Simbol s = this.simbolTable.getSimbol(lhn.name);
				  if(s == null){
					  System.out.println("Error on line " + this.lineNo + ": Simbol " + lhn.name + " is not known.");
					  this.decrementMaxErros();
					  return false;
				  }else if(s.isInitialized == false 
						  && !(info.toString().split(" ")[0].equals("IF:") && s.ifInitialized)
						  && !(info.toString().split(" ")[0].equals("ELSE:") && s.elseInitialized)){
					  System.out.println("info: " + info.toString());
					  if(s.condInitialized || this.simbolTable.getScope(lhn.name).equals("global")) {
						  System.out.println("Error on line " + this.lineNo + ": Simbol " + lhn.name + " may not have been initiated.");
					  }else {
						  System.out.println("Error on line " + this.lineNo + ": Simbol " + lhn.name + " has not been initiated.");
						  this.decrementMaxErros();
						  return false;
					  }
				  }
					  lhn.type = s.getType().getName();
			  }
		  }
		  
		  this.type = lhn.type;
		  
		  return result;
	}
  
}
/* JavaCC - OriginalChecksum=c9d5eb86f9eb1656bb1ef2e1876f7e1b (do not edit this line) */
