/* Generated By:JJTree: Do not edit this line. ASTerror_skipto.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTerror_skipto extends SimpleNode {
  public ASTerror_skipto(int id) {
    super(id);
  }

  public ASTerror_skipto(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=31ec6ea9e64f9f9c2c031ee27eeadfee (do not edit this line) */
