/* Generated By:JJTree: Do not edit this line. ASTELSE_BODY.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTELSE_BODY extends SimpleNode {
  public ASTELSE_BODY(int id) {
    super(id);
  }

  public ASTELSE_BODY(Jmm p, int id) {
    super(p, id);
  }
  
  public boolean doSemanticAnalysis(StringBuilder info) {
	  
	  boolean result = true;
	  StringBuilder info_temp = new StringBuilder("ELSE:");
	  if(this.children != null) {
		  for(Node node : this.children) {
			  boolean r = ((SimpleNode) node).doSemanticAnalysis(info_temp);
			  result = result && r;
		  }
	  }
	  
	  //System.out.println(info_temp);
	  
	  String [] assignVars = info_temp.toString().split(" ");
	  for(int i = 1; i < assignVars.length; i++) {
		  //System.out.println(assignVars[i] + "  " + this.simbolTable.getSimbol(assignVars[i]).ifInitialized + "  " + info.toString());
		  info.append(" " + assignVars[i]);
		  if(this.simbolTable.getSimbol(assignVars[i]).elseInitialized) {
			  this.simbolTable.getSimbol(assignVars[i]).elseInitialized = false;
			  this.simbolTable.getSimbol(assignVars[i]).init--;
			  
			  if(info.toString().split(" ")[0].equals("IF:")) {
				  if(this.simbolTable.getSimbol(assignVars[i]).init == 0) {
					  this.simbolTable.getSimbol(assignVars[i]).init++;  
				  }
				  this.simbolTable.getSimbol(assignVars[i]).ifInitialized = true;
			  }
			  else if(info.toString().split(" ")[0].equals("ELSE:")) {
				  if(this.simbolTable.getSimbol(assignVars[i]).init == 0) {
					  this.simbolTable.getSimbol(assignVars[i]).init--;  
				  }
				  this.simbolTable.getSimbol(assignVars[i]).elseInitialized = true;
			  }
			  else {
				  if( this.simbolTable.getSimbol(assignVars[i]).init == 0)
					  this.simbolTable.getSimbol(assignVars[i]).isInitialized = true;
				  else 
					  this.simbolTable.getSimbol(assignVars[i]).init = 0;
			  }
			  
			  
		  }
		  
	  }
	  
	  return result;
	  
  }

}
/* JavaCC - OriginalChecksum=735bbef29457db2e2da2cfc846e774dd (do not edit this line) */
