/* Generated By:JJTree: Do not edit this line. ASTFUNCTION.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFUNCTION extends SimpleNode {
  public ASTFUNCTION(int id) {
    super(id);
  }

  public ASTFUNCTION(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ff7d338328dd91daef21bbda214f1c59 (do not edit this line) */
