/* Generated By:JJTree: Do not edit this line. ASTINDEX.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTINDEX extends SimpleNode {
  public ASTINDEX(int id) {
    super(id);
  }

  public ASTINDEX(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=75a505014c72b262f4da0b2d7b88d8aa (do not edit this line) */
