/* Generated By:JJTree: Do not edit this line. ASTIF_STATEMENT.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIF_STATEMENT extends SimpleNode {
  public ASTIF_STATEMENT(int id) {
    super(id);
  }

  public ASTIF_STATEMENT(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=33daf199c16435c0573e99d15ebae32e (do not edit this line) */
