/* Generated By:JJTree: Do not edit this line. ASTMETHOD.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMETHOD extends SimpleNode {
  public ASTMETHOD(int id) {
    super(id);
    this.has_scope = true;
  }

  public ASTMETHOD(Jmm p, int id) {
    super(p, id);
    this.has_scope = true;
  }

  public boolean createTable() {
    if (this.parent == null) {
      System.out.println("Null Parent");
    }
    else {this.functionTable = ((SimpleNode)this.parent).functionTable;}
    if (this.functionTable.addFunction(this.type, this.name, this.simbolTable) == false) {
      System.out.println("Error adding function" + this.type + " " + this.name);
      return false;
    }
    else return true;
  }

}
/* JavaCC - OriginalChecksum=388f83dfa80f76895eee35b7c442ec5f (do not edit this line) */
