/* Generated By:JJTree: Do not edit this line. ASTMETHOD_BODY.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMETHOD_BODY extends SimpleNode {
  public ASTMETHOD_BODY(int id) {
    super(id);
    this.has_scope = true;
  }

  public ASTMETHOD_BODY(Jmm p, int id) {
    super(p, id);
    this.has_scope = true;
  }

}
/* JavaCC - OriginalChecksum=b95b49084b42f7b5a26cb3a8ac505539 (do not edit this line) */
