import java.util.ArrayList;
import java.util.List;


/* Generated By:JJTree: Do not edit this line. ASTMETHOD.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMETHOD extends SimpleNode {
  public ASTMETHOD(int id) {
    super(id);
    this.has_scope = true;
  }

  public ASTMETHOD(Jmm p, int id) {
    super(p, id);
    this.has_scope = true;
  }

  public boolean createTable() {
	  
	boolean result = true;
	  
	if(this.parent != null) {
		 this.functionTable = ((SimpleNode)this.parent).functionTable;
		 this.descriptors = ((SimpleNode)this.parent).descriptors;
	}
  
	if(this.has_scope == false && this.parent != null) {
		  this.simbolTable = ((SimpleNode)this.parent).simbolTable;
	}
	else if(this.has_scope == true){
	  this.simbolTable = new SimbolTable();
	  if(this.parent != null){
		  this.simbolTable.setParent( ( (SimpleNode)this.parent ).simbolTable);
	  }
	}
	this.simbolTable.setParam(true);

	List<Descriptor> listDesc = new ArrayList<>();

	for(int i = 0; i < this.jjtGetNumChildren() - 1; i++) {

		listDesc.add( new Descriptor(((SimpleNode)this.children[i]).type, this.simbolTable)); 
	}
	

	
	//if (this.functionTable.addFunction(this.type,this.descriptors.getDescriptor("this").name, this.name, this.simbolTable, this.is_static) == false) {
	if (this.functionTable.addFunction(this.type,this.descriptors.getDescriptor("this").name, this.name, this.simbolTable, this.is_static, listDesc) == false) {
	    System.out.println(/*"Line " + this.lineNo + ": "+*/ "Error adding function" + this.type + " " + this.name);
	    result = false;
	  }
	
	if(this.children != null) {
	  for(Node node : this.children) {
		  boolean r = ((SimpleNode) node).createTable();
		  result = result && r;
	  }
	}
	
	return result;
  }


}
/* JavaCC - OriginalChecksum=388f83dfa80f76895eee35b7c442ec5f (do not edit this line) */
