/* Generated By:JJTree: Do not edit this line. ASTMETHOD_BODY.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMETHOD_BODY extends SimpleNode {
  public ASTMETHOD_BODY(int id) {
    super(id);
    this.has_scope = true;
  }

  public ASTMETHOD_BODY(Jmm p, int id) {
    super(p, id);
    this.has_scope = true;
  }
  
  public boolean createTable() {
	  
	  
	  if(this.parent != null) {
		 this.functionTable = ((SimpleNode)this.parent).functionTable;
		 this.descriptors = ((SimpleNode)this.parent).descriptors;
	  }
	  
	  if(this.has_scope == false && this.parent != null) {
		  this.simbolTable = ((SimpleNode)this.parent).simbolTable;
	  }
	  else if(this.has_scope == true){
		  this.simbolTable = new SimbolTable();
		  if(this.parent != null){
			  this.simbolTable.setParent( ( (SimpleNode)this.parent ).simbolTable);
		  }
	  }
	  this.simbolTable.setLocal(true);
	  
	  boolean result = true;
	   
	  if(this.children != null) {
		  for(Node node : this.children) {
			  boolean r = ((SimpleNode) node).createTable();
			  result = result && r;
		  }
	  }

	  return result;
  }

}
/* JavaCC - OriginalChecksum=b95b49084b42f7b5a26cb3a8ac505539 (do not edit this line) */
