/* Generated By:JJTree: Do not edit this line. ASTMETHOD_PROT.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMETHOD_PROT extends SimpleNode {
  public ASTMETHOD_PROT(int id) {
    super(id);
  }

  public ASTMETHOD_PROT(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=608ef272b9b0d187da12864c2ee16447 (do not edit this line) */
