/* Generated By:JJTree: Do not edit this line. ASTNEW_IDENTIFIER.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNEW_IDENTIFIER extends SimpleNode {
  public ASTNEW_IDENTIFIER(int id) {
    super(id);
  }

  public ASTNEW_IDENTIFIER(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7c73e3b97cb23875cadd21c58e42f93f (do not edit this line) */
