/* Generated By:JJTree: Do not edit this line. ASTNEW_INT_ARR.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNEW_INT_ARR extends SimpleNode {
  public ASTNEW_INT_ARR(int id) {
    super(id);
  }

  public ASTNEW_INT_ARR(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ce4cf0d753328eefc3373506e1924bc3 (do not edit this line) */
