/* Generated By:JJTree: Do not edit this line. ASTNOT_EXPRESSION.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNOT_EXPRESSION extends SimpleNode {
  public ASTNOT_EXPRESSION(int id) {
    super(id);
  }

  public ASTNOT_EXPRESSION(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4824ff70676d93ce946c932c055e30e6 (do not edit this line) */
