/* Generated By:JJTree: Do not edit this line. ASTOPERATOR.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOPERATOR extends SimpleNode {
  public ASTOPERATOR(int id) {
    super(id);
  }

  public ASTOPERATOR(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ea0b61aa43566c51566716de5ad918ef (do not edit this line) */
