/* Generated By:JJTree: Do not edit this line. ASTOPERATOR.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTOPERATOR extends SimpleNode {
  public ASTOPERATOR(int id) {
    super(id);
  }

  public ASTOPERATOR(Jmm p, int id) {
    super(p, id);
  }
  
  
public boolean doSemanticAnalysis(StringBuilder info) {
	  
	  
	  boolean result = true;
	  
	  if(this.children != null) {
		  for(Node node : this.children) {
			  boolean r = ((SimpleNode) node).doSemanticAnalysis(info);
			  result = result && r;
		  }
	  }
	  
	  SimpleNode lhn  = (SimpleNode) this.children[0];
	  SimpleNode rhn  = (SimpleNode) this.children[1];
	  if(lhn.toString().equals("IDENTIFIER")) {
		  Simbol s = this.simbolTable.getSimbol(lhn.name);
		  if(s == null){
			  System.out.println("Line " + lhn.lineNo + ": Simbol " + lhn.name + " is not known.");
			  return false;
		  }else if(s.isInitialized == false 
				  && !(info.toString().split(" ")[0].equals("IF:") && s.ifInitialized)
				  && !(info.toString().split(" ")[0].equals("ELSE:") && s.elseInitialized)){
			  	//System.out.println("info: " + info.toString() + " " + s.isInitialized + " " + s.ifInitialized + " " + s.elseInitialized + " " + s.condInitialized);
				  
			  if(s.condInitialized || this.simbolTable.getScope(lhn.name).equals("global")) {
				  System.out.println("Line " + lhn.lineNo + ": Simbol " + lhn.name + " may not have been initiated.");
			  }else {
				  System.out.println("Line " + lhn.lineNo + ": Simbol " + lhn.name + " has not been initiated.");
				  return false;
				 }
		  }
			  lhn.type = s.getType().getName();
	  }
	  if(rhn.toString().equals("IDENTIFIER")) {
		  Simbol s = this.simbolTable.getSimbol(rhn.name);
		  if(s == null){
			  System.out.println("Line " + rhn.lineNo + ": Simbol " + rhn.name + " is not known.");
			  return false;
		  }else if(s.isInitialized == false 
				  && !(info.toString().split(" ")[0].equals("IF:") && s.ifInitialized)
				  && !(info.toString().split(" ")[0].equals("ELSE:") && s.elseInitialized)){
				  if(s.condInitialized || this.simbolTable.getScope(rhn.name).equals("global")) {
					  System.out.println("Line " + rhn.lineNo + ": Simbol " + rhn.name + " may not have been initiated.");
				  }else {
					  System.out.println("Line " + rhn.lineNo + ": Simbol " + rhn.name + " has not been initiated.");
					  return false;
				  }
		  }
			  rhn.type = s.getType().getName();
		  
	  }
	  
	  if(result == false)
		  return false;
	  
	  //System.out.println(lhn.type + "  " + lhn.toString() + "  " + lhn.name);
	  //System.out.println(rhn.type + "  " + rhn.toString() + "  " + rhn.name);
	  if(!lhn.type.equals(rhn.type)) {
		  System.out.println("Line " + this.lineNo + ": Types incompatible " + lhn.type + " and " + rhn.type + ".");
		  result = false;
	  }
	  
	  if(this.name.equals("&&")) {
		  if(!lhn.type.equals("boolean")) { System.out.println("Line " + this.lineNo + ": " +  lhn.type  + " operation must be boolean."); result = false; }
		  else if(!lhn.type.equals("boolean")) { System.out.println("Line " + this.lineNo + ": " +  rhn.type  + " operation must be boolean."); result = false; }
		  else this.type = "boolean";
	  }else {
		  if(!lhn.type.equals("int")) { System.out.println("Line " + this.lineNo + ": " + lhn.type  + " operation must be int."); result = false; }
		  else if(!lhn.type.equals("int")) { System.out.println("Line " + this.lineNo + ": " +  rhn.type  + " operation must be int."); result = false; }
		  else
			  if(this.name.equals("<")) this.type = "boolean";
			  else this.type = "int";
	  }
	  return result;
  }

}
/* JavaCC - OriginalChecksum=ea0b61aa43566c51566716de5ad918ef (do not edit this line) */
