/* Generated By:JJTree: Do not edit this line. ASTPARAM.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPARAM extends SimpleNode {
  public ASTPARAM(int id) {
    super(id);
  }

  public ASTPARAM(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e8400635e0a43f55ab72de92a032b2f8 (do not edit this line) */
