/* Generated By:JJTree: Do not edit this line. ASTProgram.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTProgram extends SimpleNode {
  public ASTProgram(int id) {
    super(id);
    this.has_scope = true;
  }

  public ASTProgram(Jmm p, int id) {
    super(p, id);
    this.has_scope = true;
  }


  public boolean createTable() {

    boolean result = true;

    this.functionTable = new FunctionTable();

    this.simbolTable = new SimbolTable();


    if(this.children != null) {
      for(Node node : this.children) {
        boolean r = ((SimpleNode) node).createTable();
        result = result && r;
      }
    }
    
    return result;
  }

  

}
/* JavaCC - OriginalChecksum=985279cf398b94f70dee66131d101454 (do not edit this line) */
