import java.io.FileOutputStream;
import java.io.IOException;
/* Generated By:JJTree: Do not edit this line. ASTProgram.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTProgram extends SimpleNode {
  public ASTProgram(int id) {
    super(id);
    this.has_scope = true;
  }

  public ASTProgram(Jmm p, int id) {
    super(p, id);
    this.has_scope = true;
  }


  public boolean createTable() {

    boolean result = true;

    this.functionTable = new FunctionTable();
    this.simbolTable = new SimbolTable();
    this.descriptors = new DescriptorTable();
    
    this.descriptors.addDescriptor("int",this.simbolTable);
    this.descriptors.addDescriptor("boolean",this.simbolTable);
    this.descriptors.addDescriptor("String",this.simbolTable);
    this.descriptors.addDescriptor("int[]",this.simbolTable,this.descriptors.getDescriptor("int"));
    this.descriptors.addDescriptor("String[]",this.simbolTable,this.descriptors.getDescriptor("String"));

    if(this.children != null) {
      for(Node node : this.children) {
        boolean r = ((SimpleNode) node).createTable();
        result = result && r;
      }
    }
    
    return result;
  }
  
public void printTables() {
	  
	  if(this.has_scope) {
		  String str = "I have scope:   " + toString();
		  if(this.parent != null) str+= "    my parent is:    " + ( (SimpleNode)this.parent ).toString();
		  System.out.println(str);
		  this.simbolTable.printTable();
	  }
	  this.functionTable.printTable();
	  
	  if(this.children != null) {
		  for(Node node : this.children) {
			  ((SimpleNode) node).printTables();
		  }
	  }
	  
  }

public void writeJasminFile(String fileName) {
    String jasminFileName = fileName.replaceFirst("[.][^.]+$", "") + ".j";
	  System.out.println("FILE " + jasminFileName);

    try {
      FileOutputStream fstream = new FileOutputStream(jasminFileName);

   /*   BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(fstream));
      bw.write(root.accept(new JasminGenerator()));
    */  //bw.close();
    } catch (IOException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
}

	
  

}
/* JavaCC - OriginalChecksum=985279cf398b94f70dee66131d101454 (do not edit this line) */
