/* Generated By:JJTree: Do not edit this line. ASTPARAMS.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPARAMS extends SimpleNode {
  public ASTPARAMS(int id) {
    super(id);
  }

  public ASTPARAMS(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a5158f9e71aa7def2396a0c068580711 (do not edit this line) */
