/* Generated By:JJTree: Do not edit this line. ASTTHIS.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTHIS extends SimpleNode {
  public ASTTHIS(int id) {
    super(id);
  }

  public ASTTHIS(Jmm p, int id) {
    super(p, id);
  }
  
  public boolean doSemanticAnalysis(StringBuilder info) throws SemanticException {
	  
	  boolean result = true;
	  
	  if(this.children != null) {
		  for(Node node : this.children) {
			  boolean r = ((SimpleNode) node).doSemanticAnalysis(info);
			  result = result && r;
		  }
	  }
	  
	  SimpleNode method = (SimpleNode)this.jjtGetParent();
	  while(!method.toString().equals("METHOD")) {
		  method = (SimpleNode)method.jjtGetParent();
	  }
	  if(method.is_static) {
		  System.out.println("Error on line " + this.lineNo + ", column " + this.columnNo + ": Non static variable cannot be refereced from a static context");
		  this.decrementMaxErros();
		  return false;
	  }
	  
	  return result;
	  
  }
  
}
/* JavaCC - OriginalChecksum=b26643b4ed369a2582e91f02974d80c0 (do not edit this line) */
