/* Generated By:JJTree: Do not edit this line. ASTVAR.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVAR extends SimpleNode {
  public ASTVAR(int id) {
    super(id);
  }

  public ASTVAR(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3d5ba3dbf45f9bb899864a825571601d (do not edit this line) */
