/* Generated By:JJTree: Do not edit this line. ASTWHILE.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWHILE extends SimpleNode {
  public ASTWHILE(int id) {
    super(id);
  }

  public ASTWHILE(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=796aee3bf89e5c37a0b70184cd5a1b31 (do not edit this line) */
